name: AWS OIDC Connect Demo

on:
  push

env:
  AWS_REGION : "ap-south-1"   

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  DemoOIDC:
    runs-on: ubuntu-latest  # Use GitHub-hosted runner 'ubuntu-latest'
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::121263836368:role/tts-test-role-2
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

      - name: Print AWS SSM Parameter
        run: aws ssm get-parameter --name=hello_aws-gh-oidc --query Parameter.Value

      - name: Print assumed role
        run: aws sts get-caller-identity
