name: Deploy FastAPI App

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "ap-south-1"
  AZURE_REGION: "eastus"

permissions:
  id-token: write # Needed for OIDC-based role assumption
  contents: read  # Required for actions/checkout

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Install pytest
      - name: Install pytest
        run: pip install pytest

      # Step 5: Run pytest with verbose mode
      - name: Run pytest
        run: pytest -v

      # Step 6: Configure AWS credentials using OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::121263836368:role/tts-role  # Replace with your IAM Role ARN
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: fastapi-session

      # Step 7: Upload static files and deploy app to S3 or any other service (if applicable)
      - name: Upload static files to S3
        run: |
          aws s3 sync ./static s3://text-to-speech-files-123/static/

      # Step 8: Run the FastAPI app (you might replace this with deployment commands)
      - name: Start FastAPI app
        run: |
          uvicorn app:app --host 0.0.0.0 --port 8000
